"""initial schema: customers, policies, claims

Revision ID: 7cb52c44501f
Revises: 
Create Date: 2026-07-04 06:20:33.474124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb52c44501f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('policies',
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('policy_issue_date', sa.Date(), nullable=False),
    sa.Column('coverage_limit', sa.Float(), nullable=False),
    sa.Column('deductible', sa.Float(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_table('claims',
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('loss_date', sa.Date(), nullable=False),
    sa.Column('loss_amount', sa.Float(), nullable=False),
    sa.Column('cause', sa.String(), nullable=False),
    sa.Column('final_payout', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.policy_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claims')
    op.drop_table('policies')
    op.drop_table('customers')
    # ### end Alembic commands ###
